version: "3.9"

services:

  zeo:
    image: sudishrestha/regvit-senaite:0.0.1
    container_name: regvit-zeo
    command: zeo
    volumes:
      - ./data:/data

  senaite:
    container_name: regvit-senaite
    image: sudishrestha/regvit-senaite:0.0.1
    ports:
      - 9099:8080
    links:
      - zeo
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024MB
    environment:
      ZEO_ADDRESS: "zeo:8080"


volumes:
  data:
    external: true
